### ISSUE TITLE
Game crashes when in Twilight Forest

### ISSUE THREAD

**Issue by Swifts12345** [spoorn/sodium-forge#54] opened 2021-06-29 10:53 UTC
### Reproduction Steps
Following from a [https://github.com/spoorn/sodium-forge/issues/38#issuecomment-869530197](now closed issue) the other day, I removed the Dynamic Surroundings mod as that was supposedly the one causing my game to freeze in the Twilight Forest. I tried again in the Twilight Forest in my mod pack and I had an other freeze. I decided to make a test pack which only had Sodium Reforged and Twilight Forest to see if it worked. While I was able to go a bit farther without any freezes, my game did eventually crash at random.

1. Enter Twilight Forest in Creative
2. Fly for a few chunks
3. Game crashes

### Crash Report File
[crash-2021-06-29_11.44.58-client.txt](https://github.com/spoorn/sodium-forge/files/6732796/crash-2021-06-29_11.44.58-client.txt)

### [Optional] Server/Client logs
Sometimes a crash won't output a crash report file.  In your `logs/` folder, there should be a `latest.log` and/or `debug.log`.  You may include the **END** of this log showing any errors and a few surrounding lines of context.  Don't include the entire file as the first few lines of the log may contain some information of your file system.

**Comment by spoorn** [comment] 2021-06-29 17:44
Dupe of https://github.com/spoorn/sodium-forge/issues/56

**Closed as completed by spoorn** 2021-06-29 17:44 UTC
Labels: duplicate
