### ISSUE TITLE
Dynamic Trees Render Incorrectly

### ISSUE THREAD

**Issue by WenXin20** [spoorn/sodium-forge#30] opened 2021-06-19 00:38 UTC
### Expected Behavior
- Dynamic Trees should render correctly.

### Actual Behavior
- Dynamic cactus and tree roots are not connected visually.
- Dynamic tree trunks have a slight disconnection. 
  - Disabling the option `Use Compact Vertex Format` fixes this.

### Reproduction Steps
1. Plant a pipe cactus seed on sand
2. Plant a jungle pod on grass
3. Bonemeal cactus once or twice
4. Bonemeal jungle pod until roots grow

### Attachments
![2021-06-18_19 04 31](https://user-images.githubusercontent.com/12000593/122625610-c4fe2480-d06b-11eb-94bd-5d8a76e514c6.png)
![2021-06-18_19 03 48](https://user-images.githubusercontent.com/12000593/122625612-c62f5180-d06b-11eb-92e3-4707e529c0ac.png)

### Mods list
- [`Dynamic Trees v0.10.0-beta16`](https://www.curseforge.com/minecraft/mc-mods/dynamictrees)
- [`Dynamic Trees Plus v0.1.0-beta9`](https://www.curseforge.com/minecraft/mc-mods/dynamictreesplus)

### System Information

- Java Version: [1.8.0_51]
- CPU: [4x AMD A12-9720P]
- GPU: [AMD Radeon R7]
- `Sodium Reforged v2.2`

**Comment by spoorn** [comment] 2021-06-19 01:36
Dupe of https://github.com/spoorn/sodium-forge/issues/17

**Closed as completed by spoorn** 2021-06-19 01:36 UTC
Labels: bug

**Comment by WenXin20** [comment] 2021-06-19 02:22
Ah, oops, missed it when looking at the open issues.
