### ISSUE TITLE
Had this problem with water physics overhaul which uses SKDS core

### ISSUE THREAD

**Issue by Mr-Syntax** [spoorn/sodium-forge#74] opened 2021-07-08 00:35 UTC
Mixin apply failed mixins.skds_core.json:multithreading.ServerChunkProviderMixin -> net.minecraft.world.server.ServerChunkProvider: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/server/ServerChunkProvider::aaa with priority 1000 cannot inject into net/minecraft/world/server/ServerChunkProvider::func_212849_a_(IILnet/minecraft/world/chunk/ChunkStatus;Z)Lnet/minecraft/world/chunk/IChunk; merged by me.jellysquid.mods.sodium.mixin.world.chunk_access.ServerChunkManagerMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.skds_core.json:multithreading.ServerChunkProviderMixin -> Prepare Injections ->  -> redirect$zfg000$aaa(IILnet/minecraft/world/chunk/ChunkStatus;Z)Ljava/lang/Thread; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/server/ServerChunkProvider::aaa with priority 1000 cannot inject into net/minecraft/world/server/ServerChunkProvider::func_212849_a_(IILnet/minecraft/world/chunk/ChunkStatus;Z)Lnet/minecraft/world/chunk/IChunk; merged by me.jellysquid.mods.sodium.mixin.world.chunk_access.ServerChunkManagerMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.skds_core.json:multithreading.ServerChunkProviderMixin -> Prepare Injections ->  -> redirect$zfg000$aaa(IILnet/minecraft/world/chunk/ChunkStatus;Z)Ljava/lang/Thread; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:93)
	at net.minecraft.util.registry.WorldGenRegistries.func_243672_e(WorldGenRegistries.java:39)
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$678/471388731.get(Unknown Source)
	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$684/1228926394.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
	at net.minecraft.client.main.Main$$Lambda$625/1131519640.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
02:34:55.854
monitor
Process Monitor
Process crashed with exit code 1

forge 36.1.31 minecraft 1.16.5

**Comment by spoorn** [comment] 2021-07-08 04:17
dupe of https://github.com/spoorn/sodium-forge/issues/50

**Closed as completed by spoorn** 2021-07-08 04:17 UTC
Labels: duplicate, crash
