### ISSUE TITLE
Sodium Not working with More Villagers mod

### ISSUE THREAD

**Issue by Explode007** [spoorn/sodium-forge#20] opened 2021-06-17 17:00 UTC
### Expected Behavior
Villagers from more villagers can interact with their work block and get the profession they should get in respect to the modded blocks.

### Actual Behavior
Villagers Completely ignored the work blocks and do not change professions.

### Reproduction Steps
1) Spawn villager
2) Place a work block from the "more villagers" mod
3) See that they cant acquire their profession (in fact they ignore it)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: 1.8.0_51 64bit
- CPU: RYZEN 5 3600X
- GPU: RADEON 5700XT

**Comment by spoorn** [comment] 2021-07-02 02:19
Dupe of https://github.com/spoorn/sodium-forge/issues/58

**Closed as completed by spoorn** 2021-07-02 02:19 UTC
Labels: bug, duplicate, compatibility
