### ISSUE TITLE
Crash after look in the sky

### ISSUE THREAD

**Issue by agentwolf88** [spoorn/sodium-forge#55] opened 2021-06-29 14:34 UTC
### Reproduction Steps
Loading world
look in the sky and the game crashs

### Crash Report File
[crash-2021-06-29_16.28.43-client.txt](https://github.com/spoorn/sodium-forge/files/6734235/crash-2021-06-29_16.28.43-client.txt)

**Comment by spoorn** [comment] 2021-06-29 17:53
Dupe of https://github.com/spoorn/sodium-forge/issues/56

**Closed as completed by spoorn** 2021-06-29 17:53 UTC
Labels: duplicate
